"use client";

import React, { useRef, useState } from "react";
import { UploadCloud, CheckCircle } from "lucide-react";
import { cn } from "@/lib/utils";

interface UploadZoneProps {
  onFilesSelected: (submission: string, reference: string, subName?: string, refName?: string) => void;
  disabled?: boolean;
}

export function UploadZone({ onFilesSelected, disabled }: UploadZoneProps) {
  const [activeTab, setActiveTab] = useState<"upload" | "paste">("upload");
  const [submissionCode, setSubmissionCode] = useState<string | null>(null);
  const [referenceCode, setReferenceCode] = useState<string | null>(null);
  const [submissionName, setSubmissionName] = useState<string | null>(null);
  const [referenceName, setReferenceName] = useState<string | null>(null);

  const subInputRef = useRef<HTMLInputElement>(null);
  const refInputRef = useRef<HTMLInputElement>(null);

  const handleFile = (
    file: File,
    setType: "submission" | "reference"
  ) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (e) => {
      const content = e.target?.result as string;
      if (setType === "submission") {
        setSubmissionCode(content);
        setSubmissionName(file.name);
      } else {
        setReferenceCode(content);
        setReferenceName(file.name);
      }
    };
    reader.readAsText(file);
  };

  const loadPreset = (preset: "rename" | "refactor" | "ai") => {
    if (preset === "rename") {
      setSubmissionCode(`def compute_factorial(n_val):\n    if n_val <= 1:\n        return 1\n    res = 1\n    for index in range(2, n_val + 1):\n        res *= index\n    return res\n`);
      setReferenceCode(`def compute_factorial(n):\n    if n <= 1:\n        return 1\n    total = 1\n    for i in range(2, n + 1):\n        total *= i\n    return total\n`);
      setSubmissionName("factorial_renamed.py");
      setReferenceName("factorial_original.py");
    } else if (preset === "refactor") {
      setSubmissionCode(`def is_prime_number(val):\n    if val < 2:\n        return False\n    idx = 2\n    while idx * idx <= val:\n        if val % idx == 0:\n            return False\n        idx += 1\n    return True\n`);
      setReferenceCode(`def is_prime_number(val):\n    if val < 2: return False\n    return all(val % i != 0 for i in range(2, int(val**0.5) + 1))\n`);
      setSubmissionName("prime_while_loop.py");
      setReferenceName("prime_comprehension.py");
    } else if (preset === "ai") {
      setSubmissionCode(`# Generated by AI Assistant for optimized execution\ndef binary_search(sorted_arr: list[int], target_val: int) -> int:\n    """Performs binary search with type hints and docstring."""\n    left_idx, right_idx = 0, len(sorted_arr) - 1\n    while left_idx <= right_idx:\n        mid_idx = (left_idx + right_idx) // 2\n        if sorted_arr[mid_idx] == target_val:\n            return mid_idx\n        elif sorted_arr[mid_idx] < target_val:\n            left_idx = mid_idx + 1\n        else:\n            right_idx = mid_idx - 1\n    return -1\n`);
      setReferenceCode(`def search(arr, target):\n    l, r = 0, len(arr) - 1\n    while l <= r:\n        m = (l + r) // 2\n        if arr[m] == target:\n            return m\n        if arr[m] < target:\n            l = m + 1\n        else:\n            r = m - 1\n    return -1\n`);
      setSubmissionName("binary_search_ai.py");
      setReferenceName("binary_search_original.py");
    }
  };

  const isReady = Boolean(submissionCode?.trim()) && Boolean(referenceCode?.trim());

  const handleSubmit = () => {
    if (isReady && submissionCode && referenceCode) {
      onFilesSelected(
        submissionCode,
        referenceCode,
        submissionName || "Submission.py",
        referenceName || "Reference.py"
      );
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-6">
      {/* Mode Switcher Tabs */}
      <div className="flex justify-center border-b border-slate-800 pb-4 gap-4">
        <button
          type="button"
          onClick={() => setActiveTab("upload")}
          className={cn(
            "px-5 py-2 rounded-xl text-sm font-semibold transition-all flex items-center gap-2 border",
            activeTab === "upload"
              ? "bg-blue-600/20 text-blue-400 border-blue-500/30 shadow-lg"
              : "bg-slate-900 text-slate-400 border-slate-800 hover:text-slate-200"
          )}
        >
          <UploadCloud className="w-4 h-4" />
          Upload Files
        </button>
        <button
          type="button"
          onClick={() => setActiveTab("paste")}
          className={cn(
            "px-5 py-2 rounded-xl text-sm font-semibold transition-all flex items-center gap-2 border",
            activeTab === "paste"
              ? "bg-blue-600/20 text-blue-400 border-blue-500/30 shadow-lg"
              : "bg-slate-900 text-slate-400 border-slate-800 hover:text-slate-200"
          )}
        >
          Paste Code Directly
        </button>
      </div>

      {activeTab === "upload" ? (
        <div className="flex flex-col md:flex-row gap-6">
          <DropZone
            label="Submission File"
            filename={submissionName}
            onDrop={(file) => handleFile(file, "submission")}
            onClick={() => subInputRef.current?.click()}
          />
          <input
            type="file"
            className="hidden"
            ref={subInputRef}
            accept=".py,text/plain"
            onChange={(e) => {
              if (e.target.files?.[0]) handleFile(e.target.files[0], "submission");
            }}
          />

          <DropZone
            label="Reference File"
            filename={referenceName}
            onDrop={(file) => handleFile(file, "reference")}
            onClick={() => refInputRef.current?.click()}
          />
          <input
            type="file"
            className="hidden"
            ref={refInputRef}
            accept=".py,text/plain"
            onChange={(e) => {
              if (e.target.files?.[0]) handleFile(e.target.files[0], "reference");
            }}
          />
        </div>
      ) : (
        <div className="flex flex-col md:flex-row gap-6">
          <div className="flex-1 space-y-2">
            <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider">
              Submission Code
            </label>
            <textarea
              value={submissionCode || ""}
              onChange={(e) => {
                setSubmissionCode(e.target.value);
                if (!submissionName) setSubmissionName("Submission.py");
              }}
              placeholder="Paste submission Python code here..."
              rows={8}
              className="w-full p-4 bg-slate-950 border border-slate-800 rounded-xl text-slate-100 placeholder-slate-600 font-mono text-xs focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
          <div className="flex-1 space-y-2">
            <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider">
              Reference Code
            </label>
            <textarea
              value={referenceCode || ""}
              onChange={(e) => {
                setReferenceCode(e.target.value);
                if (!referenceName) setReferenceName("Reference.py");
              }}
              placeholder="Paste reference Python code here..."
              rows={8}
              className="w-full p-4 bg-slate-950 border border-slate-800 rounded-xl text-slate-100 placeholder-slate-600 font-mono text-xs focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
        </div>
      )}

      {/* Quick Demo Presets */}
      <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
        <span className="text-xs font-medium text-slate-500">Quick Demo Presets:</span>
        <button
          type="button"
          onClick={() => loadPreset("rename")}
          className="text-xs px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-800 transition-colors"
        >
          ⚡ Variable Renaming
        </button>
        <button
          type="button"
          onClick={() => loadPreset("refactor")}
          className="text-xs px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-800 transition-colors"
        >
          🔄 Structural Refactoring
        </button>
        <button
          type="button"
          onClick={() => loadPreset("ai")}
          className="text-xs px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-800 transition-colors"
        >
          🤖 AI Rewrite
        </button>
      </div>

      <div className="flex justify-center pt-2">
        <button
          disabled={!isReady || disabled}
          onClick={handleSubmit}
          className={cn(
            "px-8 py-3 rounded-xl font-semibold transition-all shadow-lg text-sm",
            isReady && !disabled
              ? "bg-blue-600 hover:bg-blue-500 text-white shadow-blue-500/25 cursor-pointer hover:scale-105 active:scale-95"
              : "bg-slate-800 text-slate-500 cursor-not-allowed border border-slate-800"
          )}
        >
          {disabled ? "Analyzing..." : "Analyze Similarity"}
        </button>
      </div>
    </div>
  );
}

function DropZone({
  label,
  filename,
  onDrop,
  onClick,
}: {
  label: string;
  filename: string | null;
  onDrop: (file: File) => void;
  onClick: () => void;
}) {
  const [isDragOver, setIsDragOver] = useState(false);

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  };
  const handleDragLeave = () => setIsDragOver(false);
  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      onDrop(e.dataTransfer.files[0]);
    }
  };

  return (
    <div
      onClick={onClick}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
      className={cn(
        "flex-1 border-2 border-dashed rounded-lg p-8 flex flex-col items-center justify-center text-center cursor-pointer transition-colors",
        isDragOver
          ? "border-[var(--color-accent)] bg-slate-800"
          : "border-[var(--color-panel-border)] bg-[var(--color-panel)] hover:border-slate-500",
        filename && "border-[var(--color-safe)] bg-slate-800/50"
      )}
    >
      {filename ? (
        <>
          <CheckCircle className="w-10 h-10 text-[var(--color-safe)] mb-3" />
          <p className="text-sm font-mono text-slate-200">{filename}</p>
        </>
      ) : (
        <>
          <UploadCloud className="w-10 h-10 text-slate-400 mb-3" />
          <p className="text-sm font-medium text-slate-300">{label}</p>
          <p className="text-xs text-slate-500 mt-1">Drag & drop or click to browse (.py)</p>
        </>
      )}
    </div>
  );
}
